name: my_finance
description: "A new Flutter project."
# the following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. this is preferred for private packages.
publish_to: 'none' # remove this line if you wish to publish to pub.dev

# the following defines the version and build number for your application.
# a version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# in android, build-name is used as versionName while build-number used as versionCode.
# read more about android versioning at https://developer.android.com/studio/publish/versioning
# in ios, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# read more about ios versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# in windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

# dependencies specify other packages that your package needs in order to work.
# to automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. to see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4
  path: ^1.9.0
  intl: ^0.20.2
  csv: ^6.0.0
  excel: ^4.0.6
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # the "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. the lint set provided by the package is
  # activated in the analysis_options.yaml file located at the root of your
  # package. see that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# for information on the generic dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# the following section is specific to flutter packages.
flutter:

  # the following line ensures that the material icons font is
  # included with your application, so that you can use the icons in
  # the material icons class.
  uses-material-design: true

  # to add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # an image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # for details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # to add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. for
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # for details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
